### ISSUE TITLE
Error on Connection

### ISSUE THREAD

**Issue by vahidrezazadeh** [ghaninia/shipping#3]
this package passed "default" for connection to DatabaseManager and throw error.
![Capture](https://user-images.githubusercontent.com/12491459/179350780-3e71a2ec-3d6f-4991-b8e5-a4063db4dd25.PNG)

**Comment by ghaninia** [comment]
On the brunch below
https://github.com/ghaninia/shipping/tree/v2.0.3
Laravel 9 support has been added.

Thank you for your report
